### ISSUE TITLE
Fields added that aren't a default type aren't visualized. 

### ISSUE THREAD

**Issue by blyxyas** [albingroen/prismabuilder.io#45]
I don't know if this is bug just in my computer, but the fields that I add (For example, a field "Item" list in a "User") doesn't appear in the main board.

But, it generated just fine.
Example:

![Screenshot from 2022-08-01 13-16-31](https://user-images.githubusercontent.com/73757586/182136626-46b9b357-110b-4a79-859e-085f5384f7c6.png)

![Screenshot from 2022-08-01 13-16-44](https://user-images.githubusercontent.com/73757586/182136769-ac49bb29-4873-49d5-b172-e3a49ceded17.png)

Even if I refresh the page, it just doesn't appear.

**Comment by Blyxyas** [comment]
Ok I checked and it seems that this only happens for the SQLite provider

**Comment by albingroen** [comment]
@sonylomo Has a fix for this, but not sure what the behaviour should be just yet https://github.com/albingroen/prismabuilder.io/pull/51
