### ISSUE TITLE
Custom field not shown

### ISSUE THREAD

**Issue by frontalicious-martijn** [albingroen/prismabuilder.io#50]
I've added a `Task` model and added that to the `User` model as `tasks` field but it does not show in the list. When exporting the schema you can see the data is actually there. Tried it twice so that why it shows the field twice.

![image](https://user-images.githubusercontent.com/7541513/189522356-6b7fda07-f805-4666-b612-93938447444c.png)

**Comment by frontalicious-martijn** [comment]
Thank you for creating this app 🥇

**Comment by albingroen** [comment]
Should work now. It was a sqlite specific bug. https://github.com/albingroen/prismabuilder.io/pull/54
