### ISSUE TITLE
Software License

### ISSUE THREAD

**Issue by Ju99ernaut** [albingroen/prismabuilder.io#62]
Hi @albingroen, really awesome tool you've built here. I was wondering if there’s any limitations to using your code in other projects since there’s no license included in the repository?

**Comment by albingroen** [comment]
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#choosing-the-right-license

> You're under no obligation to choose a license. However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work
