### ISSUE TITLE
Dropdowns are really hard to read

### ISSUE THREAD

**Issue by ImLunaHey** [albingroen/prismabuilder.io#70]
All dropdowns have white on white text. 

![image](https://user-images.githubusercontent.com/105922175/225785994-6dc9ebd4-b0d8-46f5-ac75-d7db3e759389.png)

**Comment by albingroen** [comment]
The font should look better now!

**Comment by ImLunaHey** [comment]
That didn't fix the issue at all from what I can see. Loading the site in incognito to avoid all caches I still get the following. The white on white is the issue not the font itself.

Windows 11 with chrome and firefox, same results on both.

![image](https://user-images.githubusercontent.com/105922175/226063396-5567f588-7990-4083-9c64-664a018a8c17.png)
