### ISSUE TITLE
Importation bug

### ISSUE THREAD

**Issue by TomPere02** [albingroen/prismabuilder.io#72]
Hello,

When I import this schema it gives me this error "Make sure to import a full schema" : 

`datasource db {
  provider     = "mysql"
  url          = env("DATABASE_URL")
  relationMode = "prisma"
}

generator client {
  provider = "prisma-client-js"
}

model users {
  id       Int     @id @default(autoincrement())
  email    String  @db.VarChar(255)
  name     String? @db.VarChar(255)
  username String? @db.VarChar(255)
}
`

**Comment by markanator** [comment]
I only import my models, and that doesn't cause any issues.

**Comment by TomPere02** [comment]
> I only import my models, and that doesn't cause any issues.

Even if I import just the model, it gives me the same error.

`
model users {
id Int @id @default(autoincrement())
email String @db.VarChar(255)
name String? @db.VarChar(255)
username String? @db.VarChar(255)
}
`
