### ISSUE TITLE
Model name not able to edit

### ISSUE THREAD

**Issue by pixelsvia** [albingroen/prismabuilder.io#73]
Hello there, 
I tried to create model, and it is created with `new`, I am trying to rename it so I can add new model. 
Right now It is not editable, and in this case, not able to create new model there. Please help give functionality to make the model name editable.

![image](https://github.com/albingroen/prismabuilder.io/assets/128370840/b32182f9-6594-4082-9438-f18a35cc2c00)

**Comment by albingroen** [comment]
This is already possible :)

https://github.com/albingroen/prismabuilder.io/assets/19674362/fca4dced-9497-42f0-95e4-f23baa014bba
